name: Auto Improve / Heartbeat

on:
  # 30分ごとに自己更新（頻度は後で自由に変えてOK）
  schedule:
    - cron: "*/30 * * * *"
  # 手動実行も可
  workflow_dispatch: {}

permissions:
  contents: write   # ここが重要。コミットに必要

concurrency:
  group: auto-improve-${{ github.ref }}
  cancel-in-progress: false

jobs:
  improve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Git user
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Ensure ops dir
        run: |
          mkdir -p ops
          touch ops/last_run.log

      - name: Append heartbeat + light auto-edit
        run: |
          TS="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          {
            echo "heartbeat: $TS  sha:${GITHUB_SHA::7}"
          } >> ops/last_run.log

          # 軽量な自動編集（READMEかopsにスタンプ）
          if [ -f README.md ]; then
            printf '\n<!-- auto-edit %s -->\n' "$TS" >> README.md
          else
            printf 'Auto note at %s\n' "$TS" >> ops/notes.md
          fi

      - name: Commit if changed
        run: |
          if ! git diff --quiet; then
            git add -A
            git commit -m "chore(auto): heartbeat & light auto-edit"
            git push
            echo "pushed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes."
            echo "pushed=false" >> $GITHUB_OUTPUT
          fi
        id: commit_state