name: verify-dropbox
on:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DROPBOX_APP_KEY:        ${{ secrets.DROPBOX_APP_KEY }}
      DROPBOX_APP_SECRET:     ${{ secrets.DROPBOX_APP_SECRET }}
      DROPBOX_REFRESH_TOKEN:  ${{ secrets.DROPBOX_REFRESH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install dropbox==11.36.2
      - name: List Dropbox root
        run: |
          python - <<'PY'
          import os, dropbox
          dbx = dropbox.Dropbox(
              oauth2_refresh_token=os.getenv("DROPBOX_REFRESH_TOKEN"),
              app_key=os.getenv("DROPBOX_APP_KEY"),
              app_secret=os.getenv("DROPBOX_APP_SECRET")
          )
          # ルートは空文字！（"/" じゃない）
          res = dbx.files_list_folder("")
          print("OK:", [e.name for e in res.entries][:10])
          PY
